apiVersion: v1
kind: Service
metadata:
  name: sam-joule
  namespace: default
  annotations:
    metallb.io/address-pool: raphael-192-168-32-pool
spec:
  type: LoadBalancer
  loadBalancerClass: metallb-l2
  loadBalancerIP: 192.168.32.100
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: agent-mesh
    app.kubernetes.io/name: solace-agent-mesh
  ports:
    - name: webui-tls
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: platform-tls
      port: 4443
      protocol: TCP
      targetPort: 4443
    - name: webui
      port: 80
      protocol: TCP
      targetPort: 18000
    - name: platform
      port: 8080
      protocol: TCP
      targetPort: 8001
    - name: auth
      port: 5050
      protocol: TCP
      targetPort: 5050
